/**
 * 지구촌 TMI 블로그 주제 목록
 * 세계의 재미있고 신기한 뉴스 130개
 */

export interface Topic {
  index: number;
  slug: string;
  level: "기초편" | "중급편" | "고급편";
  category: "before" | "bidding" | "after" | "tax" | "law" | "ai";
  title: string;
  keywords: string;
  meta_description: string;
}

// 카테고리 의미
// before  = 세계 이슈 (신기한 세계 뉴스)
// bidding = 동물·자연 (동물과 자연의 놀라운 이야기)
// after   = 사람·사회 (사람과 사회의 흥미로운 이야기)
// tax     = 음식·문화 (음식과 문화의 별별 이야기)
// law     = 기록·도전 (세계 기록과 도전 이야기)
// ai      = 기술·발명 (기술과 발명의 신기한 이야기)

export const allTopics: Topic[] = [
  // ─── 기초편 (basic-001 ~ basic-043) ───────────────────
  {
    index: 1, slug: "basic-001", level: "기초편", category: "before",
    title: "세계에서 가장 작은 나라, 바티칸보다 더 작은 곳이 있다?",
    keywords: "세계 최소 국가,나우루,모나코,리히텐슈타인,미니 국가",
    meta_description: "지도에서 찾기도 힘든 세계 초소형 국가들의 놀라운 이야기를 알아봅니다.",
  },
  {
    index: 2, slug: "basic-002", level: "기초편", category: "bidding",
    title: "고양이는 왜 박스를 그렇게 좋아할까? 과학이 밝힌 진짜 이유",
    keywords: "고양이 박스,고양이 행동,반려동물,동물 심리,고양이 본능",
    meta_description: "고양이가 박스에 들어가는 행동에 숨겨진 과학적 이유를 알기 쉽게 설명합니다.",
  },
  {
    index: 3, slug: "basic-003", level: "기초편", category: "after",
    title: "세상에서 가장 행복한 나라 TOP 5, 비결이 뭘까?",
    keywords: "행복지수,핀란드,덴마크,노르웨이,세계행복보고서",
    meta_description: "매년 세계 행복 보고서에서 1위를 다투는 나라들의 행복 비결을 살펴봅니다.",
  },
  {
    index: 4, slug: "basic-004", level: "기초편", category: "tax",
    title: "코끼리 똥으로 만든 커피가 세상에서 가장 비싸다고?",
    keywords: "블랙아이보리커피,코끼리커피,세계비싼커피,태국커피,희귀커피",
    meta_description: "코끼리 위장을 통과해 만들어지는 세계에서 가장 비싼 커피의 충격적인 제조 과정.",
  },
  {
    index: 5, slug: "basic-005", level: "기초편", category: "law",
    title: "기네스북에서 가장 기상천외한 세계 기록 10가지",
    keywords: "기네스북,세계기록,황당한기록,신기한기록,기네스세계기록",
    meta_description: "믿기 어렵지만 실제로 기네스 세계 기록에 등재된 황당하고 신기한 기록들.",
  },
  {
    index: 6, slug: "basic-006", level: "기초편", category: "ai",
    title: "로봇 요리사가 일하는 레스토랑, 음식 맛은 어떨까?",
    keywords: "로봇레스토랑,로봇요리사,자동화식당,일본로봇,푸드테크",
    meta_description: "실제로 로봇이 요리하고 서빙하는 레스토랑들의 현황과 이용 후기를 알아봅니다.",
  },
  {
    index: 7, slug: "basic-007", level: "기초편", category: "before",
    title: "세계 곳곳에 숨어있는 신기한 자동판매기들",
    keywords: "신기한자판기,세계자판기,일본자판기,특이한자판기,자동판매기",
    meta_description: "랍스터부터 황금까지, 전 세계에 존재하는 믿기 어려운 자동판매기 컬렉션.",
  },
  {
    index: 8, slug: "basic-008", level: "기초편", category: "bidding",
    title: "문어가 꿈을 꾼다는 사실, 알고 계셨나요?",
    keywords: "문어수면,문어꿈,문어지능,두족류,동물수면",
    meta_description: "잠자는 동안 피부 색이 변하는 문어, 실제로 꿈을 꾸는지 과학이 밝혀낸 놀라운 사실.",
  },
  {
    index: 9, slug: "basic-009", level: "기초편", category: "after",
    title: "세계에서 가장 안전한 나라 TOP 10, 어디일까?",
    keywords: "세계평화지수,안전한나라,아이슬란드,뉴질랜드,GPI",
    meta_description: "세계 평화 지수(GPI) 기준으로 선정된 가장 안전한 나라들의 특징을 살펴봅니다.",
  },
  {
    index: 10, slug: "basic-010", level: "기초편", category: "tax",
    title: "이탈리아 마을에서 집을 1유로에 팔고 있는 진짜 이유",
    keywords: "이탈리아1유로집,시칠리아,인구소멸,유럽빈집,저렴한집",
    meta_description: "1유로(약 1500원)에 집을 파는 이탈리아 마을들의 배경과 조건을 알아봅니다.",
  },
  {
    index: 11, slug: "basic-011", level: "기초편", category: "law",
    title: "실제로 존재하는 세계에서 가장 이상한 직업들",
    keywords: "특이한직업,세계직업,잠자는직업,줄서주는직업,황당직업",
    meta_description: "줄 서주는 사람부터 전문 껌 씹는 사람까지, 실제로 돈 버는 세계의 기상천외한 직업들.",
  },
  {
    index: 12, slug: "basic-012", level: "기초편", category: "ai",
    title: "AI가 그린 그림이 경매에서 수억 원에 팔린 황당한 사건",
    keywords: "AI미술,AI작품,크리스티경매,AI예술,디지털아트",
    meta_description: "에드몽 드 벨라미 초상화부터 최근 NFT까지, AI가 만든 예술품이 수억 원에 팔린 이유.",
  },
  {
    index: 13, slug: "basic-013", level: "기초편", category: "before",
    title: "밤새 해가 지지 않는 나라에서 산다는 느낌은?",
    keywords: "백야,핀란드백야,노르웨이백야,북유럽,여름백야",
    meta_description: "여름에 해가 지지 않는 백야 현상을 경험하는 북유럽 사람들의 일상 이야기.",
  },
  {
    index: 14, slug: "basic-014", level: "기초편", category: "bidding",
    title: "플라밍고는 왜 한쪽 다리로 서 있을까? 진짜 이유",
    keywords: "플라밍고,한발서기,조류,분홍새,동물행동",
    meta_description: "수십 년 미스터리였던 플라밍고의 한쪽 다리 자세, 과학이 드디어 밝혀낸 이유.",
  },
  {
    index: 15, slug: "basic-015", level: "기초편", category: "after",
    title: "세계에서 가장 친절한 도시로 뽑힌 곳은 어디일까?",
    keywords: "친절한도시,세계친절,뉴질랜드,도시순위,여행친절",
    meta_description: "매년 발표되는 세계에서 가장 친절한 도시 순위, 한국 도시도 포함됐을까요?",
  },
  {
    index: 16, slug: "basic-016", level: "기초편", category: "tax",
    title: "세계 각지의 기상천외한 길거리 음식들",
    keywords: "세계길거리음식,특이한음식,태국길거리,전갈꼬치,세계먹거리",
    meta_description: "전갈 꼬치부터 두리안까지, 전 세계 여행자들을 놀라게 하는 기상천외한 길거리 음식들.",
  },
  {
    index: 17, slug: "basic-017", level: "기초편", category: "law",
    title: "세계에서 가장 키 큰 사람 vs 가장 작은 사람의 실제 만남",
    keywords: "기네스키,세계최장신,세계최단신,술탄쾨센,기록만남",
    meta_description: "키 251cm의 세계 최장신과 키 54.6cm의 세계 최단신이 실제로 만난 감동 이야기.",
  },
  {
    index: 18, slug: "basic-018", level: "기초편", category: "ai",
    title: "AI가 드디어 냄새를 맡을 수 있게 됐다",
    keywords: "AI후각,인공지능냄새,전자코,구글AI,후각AI",
    meta_description: "구글 딥마인드가 개발한 AI 후각 모델, 인간이 맡을 수 없는 냄새도 분류한다고?",
  },
  {
    index: 19, slug: "basic-019", level: "기초편", category: "before",
    title: "세계에서 가장 오래된 호텔, 무려 1300년 역사",
    keywords: "세계최고령호텔,니시야마온천케이운칸,일본료칸,역사호텔,오래된숙소",
    meta_description: "705년에 개업해 1300년 이상 운영 중인 세계 최고령 호텔 니시야마 온천 케이운칸의 이야기.",
  },
  {
    index: 20, slug: "basic-020", level: "기초편", category: "bidding",
    title: "앵무새가 사람 말을 따라 하는 이유가 따로 있다",
    keywords: "앵무새말하기,조류언어,앵무새지능,새의말,동물언어",
    meta_description: "단순 모방이 아닌 의사소통을 위해 말을 배우는 앵무새의 놀라운 언어 능력.",
  },
  {
    index: 21, slug: "basic-021", level: "기초편", category: "after",
    title: "세계에서 가장 오래 사는 나라는 어디일까?",
    keywords: "장수국가,일본장수,홍콩기대수명,세계장수비결,100세",
    meta_description: "평균 기대수명 세계 1위 국가들의 장수 비결과 생활 습관을 알아봅니다.",
  },
  {
    index: 22, slug: "basic-022", level: "기초편", category: "tax",
    title: "핀란드 사람들이 사우나에서 중요한 회의를 여는 이유",
    keywords: "핀란드사우나,사우나문화,북유럽문화,사우나외교,핀란드생활",
    meta_description: "핀란드 대통령도 사우나에서 외교 회의를 연다는 사실, 그 문화적 배경을 알아봅니다.",
  },
  {
    index: 23, slug: "basic-023", level: "기초편", category: "law",
    title: "올림픽 역사상 가장 황당한 실격 및 사건들",
    keywords: "올림픽실격,올림픽사건,황당올림픽,스포츠실격,올림픽역사",
    meta_description: "1904년 마라톤 코미디부터 금지 약물 파동까지, 올림픽 역사에 남은 황당한 사건들.",
  },
  {
    index: 24, slug: "basic-024", level: "기초편", category: "ai",
    title: "스마트폰 하나로 의사보다 정확하게 진단하는 AI의 등장",
    keywords: "AI진단,의료AI,피부암진단,AI의사,헬스케어AI",
    meta_description: "피부암, 당뇨 합병증 등을 의사보다 더 정확하게 진단하는 AI 의료 기술의 최신 현황.",
  },
  {
    index: 25, slug: "basic-025", level: "기초편", category: "before",
    title: "세계에서 가장 짧은 국경선은 고작 몇 미터라고?",
    keywords: "세계최단국경,스페인모로코,페뇽데알후세마스,국경이야기,세계지리",
    meta_description: "단 85미터짜리 국경부터 육지로 둘러싸인 나라까지, 세계의 신기한 국경 이야기.",
  },
  {
    index: 26, slug: "basic-026", level: "기초편", category: "bidding",
    title: "침팬지가 인간보다 기억력이 뛰어나다는 연구 결과",
    keywords: "침팬지기억력,동물지능,침팬지아이,숫자기억,일본연구",
    meta_description: "일본 교토대학 연구에서 밝혀진 충격적인 사실, 침팬지 아이가 대학생보다 숫자를 더 잘 외운다.",
  },
  {
    index: 27, slug: "basic-027", level: "기초편", category: "after",
    title: "세계에서 가장 많이 쓰이는 이름은 무엇일까?",
    keywords: "세계인기이름,흔한이름,무함마드,글로벌이름,이름통계",
    meta_description: "전 세계에서 가장 많은 사람이 사용하는 이름 TOP 10과 그 문화적 배경.",
  },
  {
    index: 28, slug: "basic-028", level: "기초편", category: "tax",
    title: "세상에서 가장 매운 음식을 먹으면 어떤 일이 벌어질까?",
    keywords: "세계최매운음식,캐롤라이나리퍼,매운음식챌린지,스코빌,고추",
    meta_description: "스코빌 지수 300만을 넘는 세계 최강의 매운 고추, 먹으면 실제로 어떤 반응이 나타날까?",
  },
  {
    index: 29, slug: "basic-029", level: "기초편", category: "law",
    title: "세계에서 가장 오래 달린 마라톤 선수의 기록",
    keywords: "최고령마라톤,파우자싱,마라톤기록,100세마라톤,시크교도",
    meta_description: "100세에도 마라톤을 완주한 파우자 싱, 세계에서 가장 오래 달린 마라톤 선수의 감동 이야기.",
  },
  {
    index: 30, slug: "basic-030", level: "기초편", category: "ai",
    title: "세계 최초 로봇 피자 가게, 주문부터 배달까지 로봇이 다 한다",
    keywords: "로봇피자,자동화피자,피자만드는로봇,푸드오토메이션,스타트업",
    meta_description: "반죽부터 토핑, 오븐, 포장까지 모든 과정을 로봇이 담당하는 완전 자동화 피자 레스토랑.",
  },
  {
    index: 31, slug: "basic-031", level: "기초편", category: "before",
    title: "인터넷이 없는 나라에서 산다는 건 어떤 의미일까?",
    keywords: "인터넷없는나라,북한인터넷,에리트레아,인터넷자유,디지털격차",
    meta_description: "전 세계에서 인터넷 접근이 가장 제한된 나라들의 사람들은 어떻게 생활할까?",
  },
  {
    index: 32, slug: "basic-032", level: "기초편", category: "bidding",
    title: "개미는 자기 몸무게의 50배를 들 수 있다는 사실",
    keywords: "개미힘,개미능력,곤충힘,자연최강,개미슈퍼파워",
    meta_description: "세상에서 가장 강한 생명체 중 하나인 개미, 몸무게 대비 얼마나 강한지 알아봅니다.",
  },
  {
    index: 33, slug: "basic-033", level: "기초편", category: "after",
    title: "세계에서 가장 어린 나이에 대학을 졸업한 아이들",
    keywords: "천재어린이,최연소졸업,신동,세계천재,어린이천재",
    meta_description: "8살에 대학 입학, 12살에 졸업... 믿기 어려운 세계 최연소 대학 졸업자들의 이야기.",
  },
  {
    index: 34, slug: "basic-034", level: "기초편", category: "tax",
    title: "음식을 손으로 먹는 나라 vs 젓가락 나라 vs 포크 나라",
    keywords: "음식문화,손으로먹기,젓가락문화,포크나라,세계식사예절",
    meta_description: "전 세계 식사 도구 문화의 분포와 각 방식이 생겨난 역사적 배경을 알아봅니다.",
  },
  {
    index: 35, slug: "basic-035", level: "기초편", category: "law",
    title: "기네스 기록에 도전하다 생긴 웃긴 에피소드 모음",
    keywords: "기네스도전실패,기네스웃음,황당기록도전,기네스비하인드,세계기록",
    meta_description: "기네스 기록 도전 과정에서 실제로 벌어진 황당하고 웃긴 사건들을 소개합니다.",
  },
  {
    index: 36, slug: "basic-036", level: "기초편", category: "ai",
    title: "감정을 읽는 AI 로봇, 외로운 노인의 친구가 되다",
    keywords: "AI로봇,감정인식,노인돌봄,소셜로봇,반려로봇",
    meta_description: "일본과 유럽에서 실제 노인 요양원에 도입된 감정 인식 AI 로봇의 따뜻한 이야기.",
  },
  {
    index: 37, slug: "basic-037", level: "기초편", category: "before",
    title: "세계에서 가장 이상한 나라 법률 TOP 10",
    keywords: "세계이상한법,황당한법,스위스법,싱가포르껌,특이한법률",
    meta_description: "싱가포르 껌 소지 금지부터 스위스의 일요일 세탁 금지까지, 세계의 황당한 법률들.",
  },
  {
    index: 38, slug: "basic-038", level: "기초편", category: "bidding",
    title: "돌고래가 거울을 보며 자신을 인식한다는 사실",
    keywords: "돌고래지능,거울테스트,자아인식동물,돌고래IQ,해양포유류",
    meta_description: "인간과 유인원만 통과한다고 알려진 거울 테스트를 통과한 돌고래의 놀라운 자아 인식 능력.",
  },
  {
    index: 39, slug: "basic-039", level: "기초편", category: "after",
    title: "12시간 이상 일하면 불법인 나라에서의 하루",
    keywords: "노동시간법,유럽노동법,워라밸국가,노동권,근로시간",
    meta_description: "법으로 하루 최대 노동 시간을 엄격히 제한하는 나라들에서 직장인의 하루는 어떨까?",
  },
  {
    index: 40, slug: "basic-040", level: "기초편", category: "tax",
    title: "두리안 냄새로 공항에서 쫓겨난 황당한 사건들",
    keywords: "두리안냄새,두리안금지,동남아과일,두리안사건,두리안비행기",
    meta_description: "과일의 왕 두리안 때문에 실제로 비행기에서 내려야 했던 황당한 사건들 모음.",
  },
  {
    index: 41, slug: "basic-041", level: "기초편", category: "law",
    title: "세계에서 가장 많이 번역된 책 TOP 5",
    keywords: "세계최다번역,성경번역,피노키오,어린왕자,번역된책",
    meta_description: "수천 개 언어로 번역된 세계의 책들, 1위는 예상대로일까 아닐까?",
  },
  {
    index: 42, slug: "basic-042", level: "기초편", category: "ai",
    title: "버려진 음식으로 새 요리를 만드는 AI, 음식 낭비를 줄이다",
    keywords: "AI음식,음식낭비AI,푸드테크,남은음식레시피,지속가능식품",
    meta_description: "냉장고에 남은 재료를 입력하면 레시피를 만들어주는 AI의 음식 낭비 절감 효과.",
  },
  {
    index: 43, slug: "basic-043", level: "기초편", category: "before",
    title: "세상에서 가장 비싼 주소에 사는 사람들의 이야기",
    keywords: "세계비싼주소,모나코,홍콩비싼집,세계부동산,억만장자동네",
    meta_description: "1㎡당 수억 원을 호가하는 세계 최고가 주소지에 실제로 사는 사람들의 생활.",
  },

  // ─── 중급편 (mid-001 ~ mid-043) ───────────────────────
  {
    index: 44, slug: "mid-001", level: "중급편", category: "before",
    title: "도쿄 지하철이 세계에서 가장 복잡하다는 게 사실일까?",
    keywords: "도쿄지하철,세계지하철,복잡한노선,일본교통,지하철비교",
    meta_description: "도쿄, 런던, 뉴욕... 세계에서 가장 복잡한 지하철 노선 비교와 초심자 생존 팁.",
  },
  {
    index: 45, slug: "mid-002", level: "중급편", category: "bidding",
    title: "1억 년 전 호박 속에 갇힌 공룡 시대의 생물, 어디서 발견됐나",
    keywords: "호박속화석,백악기화석,미얀마호박,고대곤충,공룡시대",
    meta_description: "미얀마에서 발견된 1억 년 된 호박 속 완벽하게 보존된 작은 새의 이야기.",
  },
  {
    index: 46, slug: "mid-003", level: "중급편", category: "after",
    title: "돈 없이도 행복하게 사는 세계의 원시 부족 이야기",
    keywords: "원시부족,아마존부족,행복한삶,물물교환,비화폐사회",
    meta_description: "화폐도, 스마트폰도 없이 수천 년의 방식으로 살아가는 현대 부족들의 행복한 일상.",
  },
  {
    index: 47, slug: "mid-004", level: "중급편", category: "tax",
    title: "세계에서 가장 오래된 요리법을 재현한 셰프들",
    keywords: "고대요리,수메르음식,고대이집트요리,역사요리,고고학음식",
    meta_description: "4000년 전 수메르 점토판에 적힌 레시피를 실제로 재현해본 셰프의 놀라운 실험.",
  },
  {
    index: 48, slug: "mid-005", level: "중급편", category: "law",
    title: "우사인 볼트도 지금 달리면 못 이긴다는 동물은?",
    keywords: "치타속도,동물속도비교,볼트vs동물,세계최속동물,달리기기록",
    meta_description: "치타, 매, 돛새치... 인간이 절대 이길 수 없는 자연계의 스피드 챔피언들.",
  },
  {
    index: 49, slug: "mid-006", level: "중급편", category: "ai",
    title: "AI가 수술을 집도한 세계 최초 사례의 전말",
    keywords: "AI수술,로봇수술,다빈치로봇,자율수술AI,의료혁명",
    meta_description: "인간 의사 없이 AI가 자율적으로 수술을 집도한 역사적인 최초 사례와 결과.",
  },
  {
    index: 50, slug: "mid-007", level: "중급편", category: "before",
    title: "세계의 신기한 공중전화 박스 변신 프로젝트들",
    keywords: "공중전화변신,영국전화박스,도서관전화박스,카페전화박스,재활용",
    meta_description: "사라져가는 공중전화 박스를 도서관, 카페, 제세동기 박스로 바꾼 창의적 재활용 프로젝트.",
  },
  {
    index: 51, slug: "mid-008", level: "중급편", category: "bidding",
    title: "문어는 색맹인데 어떻게 완벽한 위장술을 펼칠까?",
    keywords: "문어위장,문어색맹,두족류피부,위장술,문어능력",
    meta_description: "색을 구분 못 하는데도 주변 환경과 완벽하게 일치하는 색으로 변신하는 문어의 비밀.",
  },
  {
    index: 52, slug: "mid-009", level: "중급편", category: "after",
    title: "세계에서 성별 평등 지수 1위 나라들의 실제 생활",
    keywords: "성별평등,아이슬란드평등,성평등지수,여성지도자,북유럽평등",
    meta_description: "14년 연속 세계 성별 격차 지수 1위 아이슬란드에서의 실제 직장과 가정 생활.",
  },
  {
    index: 53, slug: "mid-010", level: "중급편", category: "tax",
    title: "곤충을 먹는 나라들, 미래 식량 혁명이 될 수 있을까?",
    keywords: "식용곤충,귀뚜라미버거,태국곤충식,미래식량,곤충단백질",
    meta_description: "20억 명이 이미 먹고 있는 곤충 요리, 지구 온난화 시대의 구원 투수가 될 수 있을까?",
  },
  {
    index: 54, slug: "mid-011", level: "중급편", category: "law",
    title: "물속에서 가장 오래 버틴 사람의 기록은 얼마나 될까?",
    keywords: "수중호흡기록,프리다이빙,세계기록,스태틱무호흡,기네스",
    meta_description: "무려 24분 37초 동안 숨을 참은 세계 기록 보유자의 훈련법과 비밀.",
  },
  {
    index: 55, slug: "mid-012", level: "중급편", category: "ai",
    title: "진짜처럼 보이는 가짜 영상, AI 딥페이크를 잡아내는 방법",
    keywords: "딥페이크탐지,AI가짜영상,딥페이크AI,영상조작,AI탐지기",
    meta_description: "딥페이크 기술이 발전할수록 이를 잡아내는 AI도 진화한다, 창과 방패의 기술 전쟁.",
  },
  {
    index: 56, slug: "mid-013", level: "중급편", category: "before",
    title: "세계에서 가장 고립된 마을, 우편배달부가 없는 이유",
    keywords: "트리스탄다쿠냐,세계최고립지,외딴섬,고립마을,영국령섬",
    meta_description: "남대서양 한가운데 약 250명이 사는 세계에서 가장 고립된 거주 지역 트리스탄 다쿠냐 이야기.",
  },
  {
    index: 57, slug: "mid-014", level: "중급편", category: "bidding",
    title: "까마귀가 인간 얼굴을 기억하고 원한을 품는다고?",
    keywords: "까마귀지능,까마귀기억력,까마귀복수,조류지능,까마귀연구",
    meta_description: "미국 시애틀 연구에서 밝혀진 충격적 사실, 까마귀는 5년 후에도 원수의 얼굴을 기억한다.",
  },
  {
    index: 58, slug: "mid-015", level: "중급편", category: "after",
    title: "SNS를 법으로 금지한 나라들, 어떻게 사람들이 살고 있나",
    keywords: "SNS금지국가,인터넷검열,중국방화벽,소셜미디어금지,디지털통제",
    meta_description: "페이스북, 인스타그램이 차단된 나라에서 사람들이 실제로 소통하는 방법들.",
  },
  {
    index: 59, slug: "mid-016", level: "중급편", category: "tax",
    title: "세계에서 가장 오래된 와이너리, 6000년의 역사",
    keywords: "세계최고령와이너리,아르메니아와인,고대와인,와인역사,아레니",
    meta_description: "아르메니아 아레니 동굴에서 발견된 6100년 된 와이너리, 인류 최초 포도주 양조의 증거.",
  },
  {
    index: 60, slug: "mid-017", level: "중급편", category: "law",
    title: "마라톤 역사상 가장 오래 걸린 완주 기록의 사연",
    keywords: "가장늦은마라톤,시조무야마다,54년마라톤,올림픽마라톤,기이한기록",
    meta_description: "1912년 올림픽 마라톤 출전 후 54년 만에 완주 처리된 일본 선수 시조 야마다의 기막힌 사연.",
  },
  {
    index: 61, slug: "mid-018", level: "중급편", category: "ai",
    title: "AI가 작곡한 음악이 차트에 오른 황당한 사건",
    keywords: "AI음악,AI작곡,음악차트AI,아이다,AI뮤지션",
    meta_description: "음악을 작곡하고 심지어 차트까지 진입한 AI 뮤지션들, 저작권은 누구의 것일까?",
  },
  {
    index: 62, slug: "mid-019", level: "중급편", category: "before",
    title: "세계에서 가장 큰 쇼핑몰, 웬만한 도시보다 넓다",
    keywords: "세계최대쇼핑몰,두바이몰,신세계몰,쇼핑몰크기,실내도시",
    meta_description: "내부에 수족관, 스키장, 아이스링크까지 있는 세계 최대 규모 쇼핑몰 TOP 5.",
  },
  {
    index: 63, slug: "mid-020", level: "중급편", category: "bidding",
    title: "강아지가 자면서 발을 움직이는 이유는 꿈 때문이다",
    keywords: "강아지꿈,강아지수면,반려견수면,개REM수면,동물꿈",
    meta_description: "개도 인간처럼 REM 수면을 하며 꿈을 꾼다는 과학적 증거와 어떤 꿈을 꾸는지 알아봅니다.",
  },
  {
    index: 64, slug: "mid-021", level: "중급편", category: "after",
    title: "세계에서 가장 많은 언어가 쓰이는 나라는 어디일까?",
    keywords: "파푸아뉴기니언어,세계언어수,다언어국가,언어다양성,소수언어",
    meta_description: "무려 800개 이상의 언어가 쓰이는 파푸아뉴기니, 이웃 마을끼리도 언어가 다른 나라.",
  },
  {
    index: 65, slug: "mid-022", level: "중급편", category: "tax",
    title: "세상에서 가장 비싼 피자 한 판의 가격은 얼마일까?",
    keywords: "세계비싼피자,명품피자,황금피자,루이스피자,사치스러운음식",
    meta_description: "식용 금박과 화이트 트러플, 랍스터 등 최고급 재료로 만든 세계 최고가 피자 TOP 5.",
  },
  {
    index: 66, slug: "mid-023", level: "중급편", category: "law",
    title: "바나나 껍질에 미끄러지는 게 과학적으로 증명됐다",
    keywords: "바나나껍질미끄럼,과학실험,이그노벨상,마찰계수,바나나과학",
    meta_description: "이그노벨상을 수상한 황당한 연구, 바나나 껍질의 마찰계수를 실제로 측정한 일본 과학자들.",
  },
  {
    index: 67, slug: "mid-024", level: "중급편", category: "ai",
    title: "로봇 경비원이 배치됐는데 계단을 못 올라가서 실패한 사건",
    keywords: "로봇경비원,보안로봇,K5로봇,로봇실패,실리콘밸리로봇",
    meta_description: "수영장에 빠지고, 계단을 못 오르고... 실제 배치된 보안 로봇들의 황당한 실패 사례 모음.",
  },
  {
    index: 68, slug: "mid-025", level: "중급편", category: "before",
    title: "세계에서 신호등이 하나도 없는 나라가 있다고?",
    keywords: "신호등없는나라,부탄신호등,교통경찰,신호등역사,부탄교통",
    meta_description: "부탄에는 신호등이 없다, 대신 교통 경찰이 수신호로 교통을 정리하는 이색적인 이유.",
  },
  {
    index: 69, slug: "mid-026", level: "중급편", category: "bidding",
    title: "연어가 태어난 강으로 돌아오는 놀라운 귀소 능력의 비밀",
    keywords: "연어귀소,연어산란,냄새귀소,연어여정,야생연어",
    meta_description: "수천 킬로미터를 헤엄쳐 정확히 태어난 강으로 돌아오는 연어의 놀라운 후각 항법 능력.",
  },
  {
    index: 70, slug: "mid-027", level: "중급편", category: "after",
    title: "전 국민이 1년에 한 번씩 이름을 바꿀 수 있는 나라",
    keywords: "이름바꾸기,덴마크이름법,아이슬란드이름,이름규정,특이한법",
    meta_description: "법적으로 이름 변경이 쉬운 나라들과 반대로 이름 선택에 엄격한 규제가 있는 나라들.",
  },
  {
    index: 71, slug: "mid-028", level: "중급편", category: "tax",
    title: "3D 프린터로 만든 음식, 이제 진짜 레스토랑에서 판다",
    keywords: "3D프린터음식,푸드프린팅,미래음식,3D초콜릿,음식기술",
    meta_description: "초콜릿, 파스타, 심지어 고기까지 3D 프린터로 출력해 파는 실제 레스토랑 이야기.",
  },
  {
    index: 72, slug: "mid-029", level: "중급편", category: "law",
    title: "세계에서 가장 긴 수염과 손톱 기록 보유자들의 이야기",
    keywords: "세계최장수염,최장손톱,기네스기록,수염기록,손톱기록",
    meta_description: "수십 년간 키운 6미터짜리 수염과 9미터짜리 손톱, 기록 보유자들의 일상은 어떨까?",
  },
  {
    index: 73, slug: "mid-030", level: "중급편", category: "ai",
    title: "AI 변호사가 실제 법정에서 피의자를 도운 최초 사건",
    keywords: "AI변호사,법률AI,법정AI,리걸테크,AI법률서비스",
    meta_description: "이어폰을 통해 AI가 실시간으로 법적 조언을 해주는 DoNotPay의 법정 실험 전말.",
  },
  {
    index: 74, slug: "mid-031", level: "중급편", category: "before",
    title: "하늘 위에 떠있는 마을, 세계의 공중 마을들",
    keywords: "공중마을,절벽마을,이탈리아절벽,스페인마을,극한마을",
    meta_description: "수직 절벽 위에, 구름 속에 자리 잡은 세계의 신비로운 공중 마을들을 소개합니다.",
  },
  {
    index: 75, slug: "mid-032", level: "중급편", category: "bidding",
    title: "거미줄이 강철보다 강하다는 사실과 그 활용법",
    keywords: "거미줄강도,거미줄과학,거미줄방탄,스파이더실크,생체재료",
    meta_description: "같은 두께로 비교하면 강철보다 5배 강한 거미줄, 방탄복과 의료 실로 활용되는 이유.",
  },
  {
    index: 76, slug: "mid-033", level: "중급편", category: "after",
    title: "세계에서 학교를 가장 오래 다니는 나라와 가장 짧게 다니는 나라",
    keywords: "세계교육기간,핀란드교육,교육시간비교,세계학교,교육시스템",
    meta_description: "학교를 20년 넘게 다니는 나라부터 6년이면 끝나는 나라까지, 세계 교육 기간의 차이.",
  },
  {
    index: 77, slug: "mid-034", level: "중급편", category: "tax",
    title: "음식에 금가루를 넣은 세계 최고가 버거, 가격은?",
    keywords: "황금버거,금박음식,세계비싼버거,사치스러운음식,명품음식",
    meta_description: "식용 금박으로 덮인 버거, 트러플을 넣은 맥주... 세계 최고가 패스트푸드들의 황당한 가격.",
  },
  {
    index: 78, slug: "mid-035", level: "중급편", category: "law",
    title: "1912년 올림픽 마라톤, 54년 만에 완주 인정된 황당한 기록",
    keywords: "시조야마다,올림픽완주,54년마라톤,기이한스포츠,역사적기록",
    meta_description: "일사병으로 쓰러진 일본 마라톤 선수, 54년 후 멕시코 국제올림픽위원회 행사에서 완주 처리.",
  },
  {
    index: 79, slug: "mid-036", level: "중급편", category: "ai",
    title: "사람보다 빠르게 소설 쓰는 AI, 이미 베스트셀러 작가가 됐다",
    keywords: "AI소설,AI작가,챗GPT소설,AI창작,자동소설",
    meta_description: "AI가 쓴 소설이 실제 베스트셀러에 올랐다, 독자들은 AI가 쓴 줄도 몰랐다.",
  },
  {
    index: 80, slug: "mid-037", level: "중급편", category: "before",
    title: "세계에서 가장 조용한 방, 들어가면 귀에서 이상한 소리가 들린다",
    keywords: "무향실,최조용한방,마이크로소프트,청각실험,절대정숙",
    meta_description: "-20.6dB을 기록한 세계에서 가장 조용한 방, 45분 이상 있으면 환청이 들리는 이유.",
  },
  {
    index: 81, slug: "mid-038", level: "중급편", category: "bidding",
    title: "식물도 고통을 느끼고 신호를 보낸다는 최신 연구",
    keywords: "식물고통,식물신호,식물의식,식물연구,식물소통",
    meta_description: "상처 입은 식물이 초음파 신호를 방출하고 화학 물질로 이웃 식물에게 경고를 보낸다.",
  },
  {
    index: 82, slug: "mid-039", level: "중급편", category: "after",
    title: "자살률이 가장 낮은 나라들의 공통적인 비결",
    keywords: "자살률통계,세계자살률,그리스,스페인,정신건강국가",
    meta_description: "자살률이 낮은 지중해 국가들의 공통점, 가족 유대감과 음식 문화가 미치는 영향.",
  },
  {
    index: 83, slug: "mid-040", level: "중급편", category: "tax",
    title: "발효 식품이 세계 각국에서 사랑받는 과학적 이유",
    keywords: "발효음식,세계발효,김치발효,장내세균,발효과학",
    meta_description: "김치, 된장, 치즈, 요거트... 세계 각지의 발효 식품이 건강에 좋은 과학적 근거.",
  },
  {
    index: 84, slug: "mid-041", level: "중급편", category: "law",
    title: "가장 빠른 시간 안에 드레스를 만든 기네스 기록의 주인공",
    keywords: "기네스패션,드레스기록,패션스피드,웨딩드레스기록,봉제기록",
    meta_description: "단 몇 분 만에 완성된 웨딩드레스, 기네스 기록에 도전한 패션 디자이너들의 이야기.",
  },
  {
    index: 85, slug: "mid-042", level: "중급편", category: "ai",
    title: "내 꿈을 영상으로 기록해주는 AI 기기가 나왔다",
    keywords: "꿈기록AI,꿈영상화,수면AI,뇌파분석,드림리코더",
    meta_description: "수면 중 뇌파를 분석해 꿈 내용을 영상으로 재구성하는 일본 연구팀의 AI 기술.",
  },
  {
    index: 86, slug: "mid-043", level: "중급편", category: "before",
    title: "물 위에 떠있는 도시, 바다 위 인공 섬 생활기",
    keywords: "인공섬생활,몰디브인공섬,두바이팜,수상도시,미래도시",
    meta_description: "바다 위에 인공적으로 만들어진 섬에 사는 사람들의 실제 일상과 생활 방식.",
  },

  // ─── 고급편 (adv-001 ~ adv-044) ───────────────────────
  {
    index: 87, slug: "adv-001", level: "고급편", category: "before",
    title: "우주에서 내려다본 지구, 우주비행사가 겪는 개요 효과",
    keywords: "개요효과,우주비행사경험,지구관찰,우주심리,오버뷰이펙트",
    meta_description: "우주에서 지구를 본 우주비행사들이 공통으로 겪는 철학적 변화, 개요 효과(Overview Effect).",
  },
  {
    index: 88, slug: "adv-002", level: "고급편", category: "bidding",
    title: "고래가 바다의 생태계를 지탱하는 숨겨진 역할",
    keywords: "고래생태계,고래배설물,탄소흡수,해양생태,고래펌프",
    meta_description: "고래의 배설물이 바다의 탄소 흡수를 돕는다는 연구, 고래 한 마리가 나무 1000그루와 같다.",
  },
  {
    index: 89, slug: "adv-003", level: "고급편", category: "after",
    title: "세계에서 가장 오래 사는 나라들의 장수 비결 심층 분석",
    keywords: "장수마을,오키나와장수,사르디니아장수,블루존,100세비결",
    meta_description: "세계 5대 장수 지역 블루존의 공통점, 식단부터 사회적 유대까지 분석합니다.",
  },
  {
    index: 90, slug: "adv-004", level: "고급편", category: "tax",
    title: "초콜릿의 역사, 고대 마야 화폐에서 세계 최고 간식으로",
    keywords: "초콜릿역사,마야카카오,아즈텍초콜릿,카카오화폐,초콜릿진화",
    meta_description: "화폐로 쓰이던 카카오 콩이 쓴 음료를 거쳐 달콤한 고체 초콜릿이 되기까지 3000년의 여정.",
  },
  {
    index: 91, slug: "adv-005", level: "고급편", category: "law",
    title: "기네스 기록을 위해 인생을 건 사람들의 놀라운 이야기",
    keywords: "기네스헌신,기네스인생,기록도전,세계기록도전,기네스중독",
    meta_description: "수십 개의 기네스 기록을 보유한 사람들, 기록 도전이 삶의 의미가 된 이유.",
  },
  {
    index: 92, slug: "adv-006", level: "고급편", category: "ai",
    title: "AI가 멸종 위기 동물의 소리를 학습해 자연 복원에 쓰이다",
    keywords: "AI생태보전,동물소리AI,멸종위기종,AI자연보호,바이오어쿠스틱",
    meta_description: "밀렵꾼 총소리를 감지하고 멸종 위기 동물 개체 수를 추적하는 AI 자연 보전 시스템.",
  },
  {
    index: 93, slug: "adv-007", level: "고급편", category: "before",
    title: "세계 7대 불가사의를 만든 고대 기술의 비밀이 밝혀지다",
    keywords: "7대불가사의,피라미드건설,마추픽추,고대기술,고고학발견",
    meta_description: "현대 기술로도 재현하기 어려운 고대 건축물, 최신 고고학 연구로 밝혀진 건설 비밀들.",
  },
  {
    index: 94, slug: "adv-008", level: "고급편", category: "bidding",
    title: "새가 자기장으로 방향을 찾는다는 사실의 과학적 원리",
    keywords: "철새자기장,조류나침반,자기수용체,철새이동,동물항법",
    meta_description: "수천 킬로미터를 비행하는 철새가 지구 자기장을 감지해 방향을 찾는 놀라운 메커니즘.",
  },
  {
    index: 95, slug: "adv-009", level: "고급편", category: "after",
    title: "세계에서 가장 많은 이민자를 받아들인 나라의 현실",
    keywords: "이민자수용,독일이민,캐나다이민,다문화사회,난민통합",
    meta_description: "이민자를 가장 많이 수용한 나라들에서 실제로 통합이 잘 이루어지고 있는지 살펴봅니다.",
  },
  {
    index: 96, slug: "adv-010", level: "고급편", category: "tax",
    title: "세계적 셰프들이 한국 음식에 열광하는 이유",
    keywords: "한국음식세계화,K푸드,한식열풍,발효음식,한국식재료",
    meta_description: "미슐랭 스타 셰프들이 찾는 한국 발효 식품과 허브, K푸드가 세계를 사로잡는 과학적 이유.",
  },
  {
    index: 97, slug: "adv-011", level: "고급편", category: "law",
    title: "하늘을 나는 자동차, 이미 실제로 판매 중인 나라들",
    keywords: "플라잉카,에어택시,하늘을나는차,PAL-V,미래교통",
    meta_description: "PAL-V, SkyDrive, Joby Aviation... 이미 인증받고 판매 또는 운행 중인 하늘을 나는 차들.",
  },
  {
    index: 98, slug: "adv-012", level: "고급편", category: "ai",
    title: "AI가 설계한 건물이 실제로 지어진 최초 사례",
    keywords: "AI건축,AI설계,자하하디드AI,건축AI,AI디자인",
    meta_description: "알고리즘이 설계한 구조물, 3D 프린터로 출력한 집... AI 건축의 최전선을 살펴봅니다.",
  },
  {
    index: 99, slug: "adv-013", level: "고급편", category: "before",
    title: "지구에서 달까지의 거리를 몸으로 느끼게 해주는 비교들",
    keywords: "달까지거리,지구달거리,우주거리감,달탐사,우주이해",
    meta_description: "달까지 38만 km, 자동차로 가면 얼마나 걸릴까? 우주의 거리를 실감 나게 느끼는 방법들.",
  },
  {
    index: 100, slug: "adv-014", level: "고급편", category: "bidding",
    title: "사마귀가 기도하는 자세를 취하는 진짜 이유",
    keywords: "사마귀기도자세,사마귀사냥,포식자사마귀,곤충행동,사마귀본능",
    meta_description: "기도하는 듯 보이는 사마귀의 앞발 자세, 실제로는 치명적인 사냥 전략임을 밝혀봅니다.",
  },
  {
    index: 101, slug: "adv-015", level: "고급편", category: "after",
    title: "문자 없이도 수천 년 문명을 이어간 사람들의 방법",
    keywords: "키푸,잉카문자,구전전통,무문자문명,기억전달",
    meta_description: "잉카의 키푸(매듭 기록), 구전 전통으로 역사를 이어온 문화들의 놀라운 기억 보존 방법.",
  },
  {
    index: 102, slug: "adv-016", level: "고급편", category: "tax",
    title: "어두운 바다에서 빛나는 음식, 바이오루미네선스의 세계",
    keywords: "발광음식,발광버섯,반딧불이음식,바다발광,생물발광",
    meta_description: "어둠 속에서 스스로 빛을 내는 식재료들, 발광 버섯 요리부터 야광 오이까지.",
  },
  {
    index: 103, slug: "adv-017", level: "고급편", category: "law",
    title: "세상에서 가장 오래된 살아있는 나무, 얼마나 됐을까?",
    keywords: "가장오래된나무,므두셀라나무,쿠르무요나무,고대나무,수령",
    meta_description: "무려 5000년 이상 살아있는 나무 므두셀라, 생명의 비밀과 위치가 비밀인 이유.",
  },
  {
    index: 104, slug: "adv-018", level: "고급편", category: "ai",
    title: "AI가 고대 문자를 해독해 수천 년의 역사를 밝히다",
    keywords: "AI고대문자,선형문자B,AI해독,고대언어AI,고고학AI",
    meta_description: "수백 년간 해독 못 한 고대 문자를 AI가 단 며칠 만에 해독한 역사적 사례들.",
  },
  {
    index: 105, slug: "adv-019", level: "고급편", category: "before",
    title: "아마존 밀림 속에 아직 발견되지 않은 부족이 있다",
    keywords: "아마존미접촉부족,고립부족,아마존탐험,원시부족,접촉금지",
    meta_description: "외부 세계와 완전히 단절된 채 살고 있는 약 100개 미접촉 부족의 존재와 보호 정책.",
  },
  {
    index: 106, slug: "adv-020", level: "고급편", category: "bidding",
    title: "산호초가 사라지면 지구에서 일어나는 일들",
    keywords: "산호초소멸,산호백화,해양생태위기,산호초역할,기후변화바다",
    meta_description: "지구 바다 면적의 0.1%지만 해양 생물의 25%를 부양하는 산호초, 사라지면 어떻게 될까?",
  },
  {
    index: 107, slug: "adv-021", level: "고급편", category: "after",
    title: "세계에서 가장 엄격한 교통 법규를 가진 나라들",
    keywords: "핀란드교통벌금,스웨덴교통,세계교통법,엄격한교통규정,교통위반",
    meta_description: "소득에 비례하는 핀란드 교통 벌금, 운전 면허에만 수년이 걸리는 나라들의 교통 문화.",
  },
  {
    index: 108, slug: "adv-022", level: "고급편", category: "tax",
    title: "세계 각국의 술 문화, 건배 한 번에 담긴 수천 년의 역사",
    keywords: "건배문화,세계술문화,乾杯,Cheers,프랑스와인문화",
    meta_description: "한국 소주, 일본 사케, 러시아 보드카... 각국 음주 문화에 담긴 역사와 예절의 의미.",
  },
  {
    index: 109, slug: "adv-023", level: "고급편", category: "law",
    title: "물로 만든 배터리, 이미 운항 중인 친환경 선박들",
    keywords: "친환경선박,수소선박,암모니아선박,그린해운,탈탄소선박",
    meta_description: "바다에서 뽑아낸 수소로 달리는 선박, 탄소 배출 제로를 향한 해운 업계의 혁명.",
  },
  {
    index: 110, slug: "adv-024", level: "고급편", category: "ai",
    title: "뇌파를 읽어 텍스트로 변환하는 기술의 최전선",
    keywords: "뇌파텍스트,BCI기술,뇌컴퓨터인터페이스,뇌파타이핑,신경공학",
    meta_description: "생각만으로 타이핑하는 시대가 온다, 뇌-컴퓨터 인터페이스 기술의 현재와 미래.",
  },
  {
    index: 111, slug: "adv-025", level: "고급편", category: "before",
    title: "지구상에서 인간이 아직 제대로 가보지 못한 곳들",
    keywords: "미탐험지역,마리아나해구,아마존오지,남극내부,미지의장소",
    meta_description: "마리아나 해구 최저점부터 아마존 밀림 깊숙한 곳까지, 아직 인간이 발을 딛지 못한 지구의 곳들.",
  },
  {
    index: 112, slug: "adv-026", level: "고급편", category: "bidding",
    title: "식물이 이웃에게 화학 신호로 위험을 알린다는 증거들",
    keywords: "식물소통,식물경보,식물화학신호,식물언어,우드와이드웹",
    meta_description: "균류 네트워크를 통해 지하로 연결된 식물들, 영양분과 경고 신호를 주고받는 숲의 인터넷.",
  },
  {
    index: 113, slug: "adv-027", level: "고급편", category: "after",
    title: "세계에서 고독감을 가장 심각하게 다루는 나라들",
    keywords: "고독부장관,외로움국가정책,영국고독장관,사회적고립,고독대책",
    meta_description: "세계 최초로 외로움 담당 장관을 임명한 영국, 고독을 공중보건 문제로 다루는 이유.",
  },
  {
    index: 114, slug: "adv-028", level: "고급편", category: "tax",
    title: "우주에서 먹는 음식은 어떤 맛일까? 우주식의 진화",
    keywords: "우주음식,우주비행사식단,우주라면,ISS음식,우주식품",
    meta_description: "치약 튜브 속 으깬 음식에서 지금은 3D 프린터 피자까지, 우주 음식 60년의 진화 이야기.",
  },
  {
    index: 115, slug: "adv-029", level: "고급편", category: "law",
    title: "인간의 한계를 뛰어넘는 초인적 능력을 가진 사람들",
    keywords: "초인적능력,인간본능,통증무감각,초기억증후군,선천적능력",
    meta_description: "통증을 전혀 못 느끼는 사람, 냄새로 병을 진단하는 사람... 실제 초인적 능력 보유자들.",
  },
  {
    index: 116, slug: "adv-030", level: "고급편", category: "ai",
    title: "AI가 기후변화 예측 정확도를 획기적으로 높이다",
    keywords: "AI기후예측,기상AI,딥러닝날씨,구글웨더,기후모델",
    meta_description: "구글 딥마인드의 GraphCast가 기존 기상 모델을 뛰어넘은 방법과 기후 예측의 미래.",
  },
  {
    index: 117, slug: "adv-031", level: "고급편", category: "before",
    title: "심해 최저점 마리아나 해구, 탐험에서 발견된 충격적인 것들",
    keywords: "마리아나해구,챌린저딥,심해탐험,해저생물,플라스틱오염",
    meta_description: "수심 11km 지구 최저점에서 발견된 새로운 생명체들, 그리고 충격적인 플라스틱 쓰레기.",
  },
  {
    index: 118, slug: "adv-032", level: "고급편", category: "bidding",
    title: "철새가 수천 킬로미터를 쉬지 않고 날 수 있는 놀라운 비밀",
    keywords: "철새비행,알래스카도요새,장거리비행,철새수면,비행기록",
    meta_description: "11일 동안 12,000km를 쉬지 않고 날아간 알래스카 도요새, 뇌의 반쪽씩 잠드는 비밀.",
  },
  {
    index: 119, slug: "adv-033", level: "고급편", category: "after",
    title: "세계에서 가장 오래 지속되는 음악 공연, 639년짜리",
    keywords: "639년음악,존케이지ORGAN2,롱플레이음악,할버슈타트,느린음악",
    meta_description: "2001년에 시작해 2640년에 끝나는 음악 공연, 독일 할버슈타트의 639년 프로젝트 이야기.",
  },
  {
    index: 120, slug: "adv-034", level: "고급편", category: "tax",
    title: "발효 식품이 장내 세균을 바꿔 뇌까지 영향을 준다는 연구",
    keywords: "장뇌축,발효음식뇌,프로바이오틱스,장내세균뇌,발효식품과학",
    meta_description: "장내 세균이 감정과 기억에 영향을 준다는 장-뇌 축 연구, 발효 식품이 우울증을 낮추는 이유.",
  },
  {
    index: 121, slug: "adv-035", level: "고급편", category: "law",
    title: "세상에서 가장 배우기 어려운 언어, 몇 년이나 걸릴까?",
    keywords: "세계어려운언어,중국어난이도,아랍어,언어학습시간,외국어난이도",
    meta_description: "미국 외교관 훈련소가 측정한 언어 난이도 분류, 가장 배우기 어려운 언어는 무엇일까?",
  },
  {
    index: 122, slug: "adv-036", level: "고급편", category: "ai",
    title: "잠수함이 필요 없는 시대, AI 수중 드론이 바다를 누비다",
    keywords: "수중드론,AI해양탐사,무인잠수정,해저탐사AI,해양로봇",
    meta_description: "탐사, 파이프라인 점검, 환경 모니터링까지 AI 수중 드론이 바꾸는 해양 산업.",
  },
  {
    index: 123, slug: "adv-037", level: "고급편", category: "before",
    title: "세계 곳곳에 숨겨진 비밀 벙커들의 이야기",
    keywords: "비밀벙커,냉전벙커,핵벙커,지하벙커,비밀장소",
    meta_description: "영국 정부 비상 통제소부터 스위스 산속 핵 벙커까지, 실제로 존재하는 비밀 지하 시설들.",
  },
  {
    index: 124, slug: "adv-038", level: "고급편", category: "bidding",
    title: "문어가 높은 지능을 증명한 실험들, IQ 테스트를 통과하다",
    keywords: "문어지능실험,문어문제해결,두족류지능,문어도구사용,연체동물지능",
    meta_description: "병 뚜껑 열기, 미로 탈출, 도구 사용까지... 척추동물이 아님에도 놀라운 지능을 보인 문어.",
  },
  {
    index: 125, slug: "adv-039", level: "고급편", category: "after",
    title: "세계에서 주 4일 근무를 도입한 나라들의 실제 결과",
    keywords: "주4일근무,아이슬란드실험,주4일제,생산성향상,노동시간단축",
    meta_description: "아이슬란드, 영국, 일본에서 진행된 주 4일 근무 실험의 놀라운 생산성 향상 결과.",
  },
  {
    index: 126, slug: "adv-040", level: "고급편", category: "tax",
    title: "세계에서 가장 독특한 방식으로 만드는 희귀 음료들",
    keywords: "희귀음료,특이한술,세계희귀음식,발효음료,전통음료",
    meta_description: "황소 정액 칵테일부터 야크 버터 차까지, 전 세계에서 실제로 마시는 가장 독특한 음료들.",
  },
  {
    index: 127, slug: "adv-041", level: "고급편", category: "law",
    title: "지구에서 가장 오래된 생물, 불멸의 해파리 이야기",
    keywords: "불멸해파리,투리토프시스,생물학적불멸,회춘동물,영원한생명",
    meta_description: "죽음 직전 다시 어린 상태로 되돌아갈 수 있는 해파리 투리토프시스 도르니이의 불멸 메커니즘.",
  },
  {
    index: 128, slug: "adv-042", level: "고급편", category: "ai",
    title: "뇌와 컴퓨터를 연결하는 브레인칩, 이미 인간에 이식됐다",
    keywords: "뉴럴링크,브레인칩,BCI이식,뇌인터페이스,뉴럴링크인간",
    meta_description: "일론 머스크의 뉴럴링크가 인간 피험자에 이식된 이후, 어떤 일이 실제로 가능해졌나.",
  },
  {
    index: 129, slug: "adv-043", level: "고급편", category: "before",
    title: "세계 곳곳에 아직 해석 못 한 고대 미스터리들",
    keywords: "고대미스터리,스톤헨지,나스카라인,보이니치필사본,미해결고대",
    meta_description: "스톤헨지의 목적, 나스카 라인의 의미... 현대 과학으로도 풀지 못한 고대의 수수께끼들.",
  },
  {
    index: 130, slug: "adv-044", level: "고급편", category: "bidding",
    title: "자연계에서 발견된 가장 놀라운 공생 관계들",
    keywords: "공생관계,악어새,공생동물,자연공생,상리공생",
    meta_description: "악어와 새, 흰개미와 곰팡이, 꽃과 벌... 서로 없으면 살 수 없는 자연의 놀라운 파트너십.",
  },
];
